# Generated by Django 5.0.6 on 2024-07-19 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_date_joined_alter_user_last_login_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined', '-updated_at', 'email'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
