# Generated by Django 5.0.6 on 2024-06-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_package_status_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='height',
            field=models.DecimalField(decimal_places=2, help_text='Metres', max_digits=15),
        ),
        migrations.AlterField(
            model_name='package',
            name='length',
            field=models.DecimalField(decimal_places=2, help_text='Inches', max_digits=15),
        ),
        migrations.AlterField(
            model_name='package',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text="Kg's", max_digits=15),
        ),
        migrations.AlterField(
            model_name='package',
            name='width',
            field=models.DecimalField(decimal_places=2, help_text='Centimetres', max_digits=15),
        ),
    ]
