# Generated by Django 5.0.6 on 2024-06-11 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_package_height_alter_package_length_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='sender_name',
            new_name='sender',
        ),
    ]
