# Generated by Django 5.0.6 on 2024-06-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_rename_sender_name_package_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='recepient_address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
