# Generated by Django 5.0.6 on 2024-06-11 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_package_recepient_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, max_length=1000, null=True)),
                ('package_id', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.package')),
                ('status_id', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.status')),
            ],
            options={
                'verbose_name': 'Tracking Event',
                'verbose_name_plural': 'Tracking Events',
                'ordering': ['-timestamp'],
            },
        ),
    ]
