# Generated by Django 5.0.6 on 2024-06-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_remove_trackingevent_status_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='estimated_time_arrival',
            field=models.IntegerField(blank=True, default=1, max_length=100),
        ),
    ]
