# Generated by Django 5.0.6 on 2024-06-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_package_estimated_time_arrival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='estimated_time_arrival',
            field=models.IntegerField(blank=True, default=1, help_text='Days', max_length=100),
        ),
    ]
